# backend/docker-compose.yml
version: "3"
services:
  php:
    image: php:8.4.6-fpm
    container_name: php-fpm
    volumes:
      - ../:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "9000:9000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
